language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install mkdocs"
# command to run tests
before_script: "mkdocs build --clean" 
script: 
- "chmod ugo+x ./push-ghpages.sh"
- "./push-ghpages.sh"